apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    networking.gke.io/neg: '{"ingressV2TrafficPolicy": {"backendPoolingPolicy": {"metadata": {"name": "STANDARD"}}}}'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
