#!/bin/sh

changed_files=$(git diff --cached --name-only -- '*.tf')
tfdirs=$(echo "$changed_files" | xargs -I{} dirname {} | sort -u)

for dir in $tfdirs; do
  pushd "$dir"
  terraform validate || exit 1
  popd
  terraform fmt -check $dir || exit 1
done
