name: Push docker image for Lab 2
on:
  push:
    paths:
      - 'gcp/lab2/**'
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_ACTIONS_SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: gcp/lab2
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID}}/devops-journey-repository/simple-app:latest
